app = "bitpulse-frontend"
primary_region = "gru"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  HOSTNAME = "0.0.0.0"

[build]
  # Build arguments passed to Dockerfile
  [build.args]
    NEXT_PUBLIC_RECAPTCHA_SITE_KEY = "6LeOolkrAAAAAIQn7H82Prb3GTRuq7SUzXREPT9I"
    NEXT_PUBLIC_SOCKET_URL = "https://bitpulse-frontend.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[machine]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[mounts]]
  source = "bitpulse_data"
  destination = "/data" 